@extends('layouts.app')
@section('title', 'Yêu cầu đổi lịch')
@section('content')
<style>.reschedule-slot{border:1px solid #d6d3d1;border-radius:12px;background:#fff;padding:12px;text-align:left;transition:.2s}.reschedule-slot:hover:not(:disabled){border-color:#10b981;transform:translateY(-2px)}.reschedule-slot.selected{border-color:#059669;background:#ecfdf5;box-shadow:0 0 0 3px rgba(16,185,129,.16)}.reschedule-slot:disabled{opacity:.55;background:#fef2f2}.form-label{display:block;margin-bottom:8px;color:#27272a;font-size:14px;font-weight:700}.form-control{width:100%;border:1px solid #d6d3d1;border-radius:10px;padding:11px 12px;font:inherit;outline:none}.form-control:focus{border-color:#10b981;box-shadow:0 0 0 4px #d1fae5}.btn{display:inline-flex;align-items:center;justify-content:center;border-radius:10px;padding:10px 16px;font-size:14px;font-weight:700;text-decoration:none;border:1px solid transparent;transition:.2s}.btn-success{background:#059669;color:#fff}.btn-success:hover{background:#047857}.btn-success:disabled{background:#a8a29e;cursor:not-allowed}.btn-light{background:#fff;color:#44403c;border-color:#d6d3d1}.btn-light:hover{background:#fafaf9}.text-secondary{color:#78716c}#slot-grid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:12px!important}#slot-grid .reschedule-slot-wrap{min-width:0;width:auto!important;padding:0!important;margin:0!important}@media(min-width:640px){#slot-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}.w-100{width:100%}</style>
<div class="mx-auto max-w-3xl px-4 py-10 sm:px-6"><div class="mb-6"><a href="{{ route('account.bookings.index') }}" class="text-sm font-bold text-emerald-700 hover:text-emerald-800">← Lịch sử đặt sân</a><h1 class="mt-3 text-3xl font-extrabold tracking-tight text-zinc-900">Yêu cầu đổi lịch</h1><p class="mt-2 text-sm text-zinc-500">{{ $booking->court->venue->name }} · {{ $booking->court->name }}</p></div><div class="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm">
<div class="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
    <strong>Lịch cũ ({{ $slotCount }} ca):</strong><br>
    @foreach($sourceBookings as $oldBooking)
        {{ $oldBooking->slot_date->format('d/m/Y') }} {{ substr($oldBooking->start_time,0,5) }}–{{ substr($oldBooking->end_time,0,5) }}
        @if (! $loop->last)<br>@endif
    @endforeach
</div>
@if(session('error'))<div class="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{{ session('error') }}</div>@endif
<form method="POST" action="{{ route('customer.booking.reschedule.store',$booking) }}">@csrf
<div class="mb-3"><label class="form-label">Ngày mới</label><input id="new-slot-date" class="form-control" type="date" min="{{ now()->toDateString() }}" name="new_slot_date" value="{{ old('new_slot_date') }}" required></div>
<input type="hidden" name="new_time_slot_ids[]" id="new-time-slot-id" disabled>
<div class="mb-3"><label class="form-label">Khung giờ mới <span class="text-secondary">(chọn đúng {{ $slotCount }} ca)</span></label><div id="slot-loading" class="text-secondary small">Chọn ngày để xem khung giờ.</div><div id="slot-grid" class="row g-2"></div></div>
<div class="mb-4"><label class="form-label">Lý do (không bắt buộc)</label><textarea class="form-control" rows="3" name="reason">{{ old('reason') }}</textarea></div><button id="submit-button" class="btn btn-success" disabled>Gửi yêu cầu</button> <a class="btn btn-light" href="{{ route('account.bookings.index') }}">Quay lại</a>
</form></div></div></div>
<script>
const dateInput=document.getElementById('new-slot-date'),grid=document.getElementById('slot-grid'),submit=document.getElementById('submit-button'),loading=document.getElementById('slot-loading'),requiredCount={{ $slotCount }};let selectedIds=[];
function syncSelected(){document.querySelectorAll('.reschedule-slot').forEach(b=>b.classList.toggle('selected',selectedIds.includes(String(b.dataset.id))));document.querySelectorAll('.slot-input').forEach(x=>x.remove());selectedIds.forEach(id=>{const i=document.createElement('input');i.type='hidden';i.name='new_time_slot_ids[]';i.value=id;i.className='slot-input';grid.appendChild(i)});submit.disabled=selectedIds.length!==requiredCount;loading.textContent=`Đã chọn ${selectedIds.length}/${requiredCount} ca.`}
async function loadSlots(){const date=dateInput.value;grid.innerHTML='';selectedIds=[];submit.disabled=true;if(!date){loading.textContent='Chọn ngày để xem khung giờ.';return}loading.textContent='Đang tải khung giờ...';try{const r=await fetch(`/api/courts/{{ $booking->court_id }}/availability?date=${encodeURIComponent(date)}`),data=await r.json(),slots=data.data??data;loading.textContent=`Chọn đúng ${requiredCount} ca trống.`;slots.forEach(slot=>{const available=slot.is_available,col=document.createElement('div'),button=document.createElement('button');col.className='reschedule-slot-wrap';button.type='button';button.dataset.id=slot.slot_id;button.disabled=!available;button.className='reschedule-slot w-100';button.innerHTML=`<strong>${slot.start_time.slice(0,5)} - ${slot.end_time.slice(0,5)}</strong><br><small class="${available?'text-success':'text-danger'}">${available?'Còn trống':'Đã đặt/không khả dụng'}</small>`;if(available)button.onclick=()=>{const id=String(slot.slot_id);selectedIds=selectedIds.includes(id)?selectedIds.filter(x=>x!==id):(selectedIds.length<requiredCount?[...selectedIds,id]:selectedIds);syncSelected()};col.appendChild(button);grid.appendChild(col)})}catch(e){loading.textContent='Không thể tải khung giờ. Vui lòng thử lại.'}}
dateInput.addEventListener('change',loadSlots);if(dateInput.value)loadSlots();
</script>
@endsection
